language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/mattn/goveralls
script:
    - go test -covermode=count -coverprofile=cover.out
    - $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci